name: CI
on:
  push:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Enable VoiceOver Automation
        uses: guidepup/setup-action@0.1.3
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - name: Check status of VoiceOver
        run: test -f "/private/var/db/Accessibility/.VoiceOverAppleScriptEnabled" && echo "VoiceOver AppleScript Control Enabled"
      - name: Run background
        run: yarn serve >/dev/null &
      - name: Run tests
        run: yarn test
      - name: Start
        run: yarn start
      - name: Run Playwright tests
        run: yarn test:e2e
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
